### ISSUE TITLE
Select database for RedisCluster

### ISSUE THREAD

**Issue by xvilo** [phpredis/phpredis#2417]
### Expected behaviour

I would like to be able to select a database for an instance of RedisCluster, the [Select method](https://github.com/phpredis/phpredis#select) is documented. But when trying this I get the following exception:

`Call to undefined method RedisCluster::select()`

Example code in this specific case:
```php
protected static function getApp_Redis_Cluster_Connection_CacheService($container)
{
    $container->privates['app.redis.cluster.connection.cache'] = $instance = new \RedisCluster(NULL, ['xxxx:6379', 'yyyy:6379', 'zzzzz:6379']);

    $instance->select(1);

    return $instance;
}
```

After inspecting the stub, it also not there. Am I missing something, is this not supported or might this be an oversight on the client side?

### Actual behaviour
Switch DB

### I'm seeing this behaviour on
- OS: linux
- Redis: 7.0.12
- PHP: 8.2
- phpredis: redis-5.3.7

### Steps to reproduce, backtrace or example script
See above code. This is a snippeted from the generated Symfony Container defintion. The container service was defined as follows:
```yaml
service:
  app.redis.cluster.connection.cache:
    class: RedisCluster
    arguments:
      $name: null
      $seeds:
        - xxxx:6379
        - yyyyy:6379
        - zzzzz:6379
    calls:
      # https://github.com/phpredis/phpredis#select
      - select: [ 1 ]
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch
