### ISSUE TITLE
Segmentation fault with doctrine/cache's RedisCache without igbinary installed

### ISSUE THREAD

**Issue by mathielen** [phpredis/phpredis#762]
RedisCache checks if Redis::SERIALIZER_IGBINARY constant is defined to check if igbinary should be used to serialize: https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L173

Using php7 and php7 branch of phpredis, this constant is always defined, regardless of igbinary being really available or not.

Thus a save to RedisCache results in a segmentation fault.

**Comment by griesi007** [comment]
Same behaviour for me

**Comment by peteward** [comment]
@griesi007 we had similar problems with igbinary which are the opposite from @mathielen. In our case we DO have igbinary installed but it's use with DoctrineCache causes seg faults and weird behaviour on CLI.

Our workaround was to not use igbinary at all by overriding it through sncredis configuration as follows:

`config.yml`:
```
snc_redis:
    class:
        # Override Doctrine Redis cache to not use the igbinary serializer.
        doctrine_cache_phpredis: Reiss\Bundle\StoreBundle\Doctrine\Cache\RedisCache
``` 

`Reiss\Bundle\StoreBundle\Doctrine\Cache\RedisCache`:
```

use Doctrine\Common\Cache\RedisCache as DoctrineRedisCache;

/**
 * Bypass IGBINARY below due to inconsistent behaviour and seg faults
 *
 * @author Adam Elsodaney <adam.elsodaney@reiss.com>
 * @author Pete Ward <peter.ward@reiss.com>
 */
class RedisCache extends DoctrineRedisCache
{
    /**
     * Returns the serializer constant to use.
     *
     * For this project, always use default PHP serializer and not igbinary.
     */
    protected function getSerializerValue()
    {
        return \Redis::SERIALIZER_PHP;
    }
}
```

Just in case this helps anyone else...
